### ISSUE TITLE
Recipe Issues - IC2 & Extra Utils

### ISSUE THREAD

**Issue by CurtisLee1994** [jaredlll08/CraftTweaker#85]
[1.10.2-3.0.14]

When this mod is installed with no scripts recipes stop working.
Most and all IC2 recipes stop working, Also Some Extra utils recipes stop working such as the Upgrade Base.

When i uninstall crafttweaker the recipes work just fine in JEI.

It also hides some recipes from IC2.

Please fix <3

**Comment by jaredlll08** [comment]
hopefully fixed in a later version, just testing it

**Comment by CurtisLee1994** [comment]
Issue still persists in newest update.

Didn't see any change :) 

Mainly IC2 & Extra Utils

Regards, Curtis

**Comment by jaredlll08** [comment]
Fixed in latest version
